apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-deployment
  labels:
    app: mylabel
    tier: frontend

spec:
  replicas: 3
  selector:
    matchLabels:
      app: mylabel
      tier: frontend

  template:
    metadata:
      labels:
        app: mylabel
        tier: frontend

    spec:
      containers:
      - name: frontend-container
        image: n91k16/kapiltodo

