apiVersion: v1        # Kubernetes API version
kind: Service         # Ye batata hai ki ye ek Service hai

metadata:
  name: frontend-nodeport   # Service ka naam
  namespace: prod           # Ye prod namespace me banegi

spec:
  type: NodePort            # Bahar se access ke liye NodePort use ho raha hai

  selector:
    app: frontend           # Ye un pods ko select karegi jinka label app=frontend hai

  ports:
    - port: 80              # Service ka internal port
      targetPort: 80       # Pod ke andar app port 80 pe chal rahi hai
      nodePort: 30080      # Node ka bahar open port (browser se yahi use hoga)
